export const OTHER_SERVICES_DATA = {
    id: "craft-services",
    nameAr: "خدمات أخرى",
    nameEn: "Other Services",
    icon: "construct",
    active: true,
    order: 2,
    type: "crafts",
    items: [
      { id: "ac-maintenance", nameAr: "صيانة تكييفات", nameEn: "AC Maintenance" },
      { id: "appliance-maintenance", nameAr: "صيانة غسالات وثلاجات", nameEn: "Washing Machine and Refrigerator Maintenance" },
      { id: "cameras-electronics", nameAr: "كاميرات واليكترونيات", nameEn: "Cameras and Electronics" },
      { id: "satellite-installation", nameAr: "صيانة دش ورسيفر", nameEn: "Satellite and Receiver Maintenance" },
      { id: "electrician", nameAr: "كهربائي", nameEn: "Electrician" },
      { id: "plumbing", nameAr: "سباكة", nameEn: "Plumbing" },
      { id: "carpentry", nameAr: "نجارة", nameEn: "Carpentry" },
      { id: "painting", nameAr: "نقاشة", nameEn: "Painting" },
      { id: "plastering", nameAr: "محارة", nameEn: "Plastering" },
      { id: "metalworks", nameAr: "حدادة", nameEn: "metalworks" },
      { id: "construction", nameAr: "اعمال بناء", nameEn: "Construction Work" },
      { id: "ceramic-flooring", nameAr: "تركيب سيراميك وارضيات", nameEn: "Ceramic and Flooring Installation" },
      { id: "marble-installation", nameAr: "تركيب رخام", nameEn: "Marble Installation" },
      { id: "advertising-design", nameAr: "تصميم الاعلانات والبنرات", nameEn: "Advertising and Banner Design" },
      { id: "screen-maintenance", nameAr: "صيانة شاشات", nameEn: "Screen Maintenance" },
      { id: "financing", nameAr: "تمويل و قروض", nameEn: "Financing" },
      { id: "aluminum-works", nameAr: "أعمال المونتال", nameEn: "Aluminum Works" },
      { id: "gas-stove-maintenance", nameAr: "صيانة بوتاجازات", nameEn: "Gas Stove Maintenance" },
      { id: "contracting-supplies", nameAr: "مقاولات وتوريدات", nameEn: "Contracting & Supplies" },
      { id: "car-towing", nameAr: "ونش رفع سيارات", nameEn: "Car Towing" },
      { id: "car-mechanic", nameAr: "ميكانيكي سيارات", nameEn: "Car Mechanic" },
      { id: "motorcycle-mechanic", nameAr: "ميكانيكي موتوسيكلات", nameEn: "Motorcycle Mechanic" },
      { id: "vespa-mechanic", nameAr: "ميكانيكي فيسبا", nameEn: "Vespa Mechanic" },
      { id: "shipping-companies", nameAr: "شركات الشحن", nameEn: "Shipping Companies" }
    ]
  };